/** Prometheus container envanteri — check.sh ile uyumlu */

export const PROMETHEUS_CONTAINERS: { id: string; label: string; critical: boolean }[] = [
  { id: 'prometheus_postgres', label: 'PostgreSQL', critical: true },
  { id: 'prometheus_timescale', label: 'TimescaleDB', critical: true },
  { id: 'prometheus_redis', label: 'Redis', critical: true },
  { id: 'prometheus_qdrant', label: 'Qdrant', critical: false },
  { id: 'prometheus_ollama', label: 'Ollama', critical: false },
  { id: 'prometheus_data', label: 'Data Ingestion', critical: true },
  { id: 'prometheus_features', label: 'Feature Engine', critical: true },
  { id: 'prometheus_context', label: 'Context Engine', critical: true },
  { id: 'prometheus_learning', label: 'Learning Engine', critical: true },
  { id: 'prometheus_sentiment', label: 'Sentiment', critical: false },
  { id: 'prometheus_macro', label: 'Macro', critical: false },
  { id: 'prometheus_signal', label: 'Signal Engine', critical: true },
  { id: 'prometheus_agents', label: 'Agent System', critical: true },
  { id: 'prometheus_shadow', label: 'Shadow System', critical: true },
  { id: 'prometheus_immunity', label: 'Immunity', critical: true },
  { id: 'prometheus_oms', label: 'OMS', critical: true },
  { id: 'prometheus_neat', label: 'NEAT', critical: false },
  { id: 'prometheus_rl', label: 'RL Agent', critical: false },
  { id: 'prometheus_autopsy', label: 'Autopsy', critical: false },
  { id: 'prometheus_rag', label: 'RAG Memory', critical: false },
  { id: 'prometheus_scenarios', label: 'Scenarios', critical: false },
  { id: 'prometheus_backtest', label: 'Backtest', critical: false },
  { id: 'prometheus_dashboard', label: 'Dashboard', critical: true },
  { id: 'prometheus_monitor', label: 'Prometheus', critical: false },
  { id: 'prometheus_grafana', label: 'Grafana', critical: false },
]
